### ISSUE TITLE
`match` with `else` not documented

### ISSUE THREAD

**Issue by callendorph** [StanzaOrg/stanzasite#10]
See Here: 

https://github.com/StanzaOrg/lbstanza/blob/0026d7f33b02891219d49730d6fa1f13ac5e9694/compiler/core-macros.stanza#L836

It seems to be defined here:

https://github.com/StanzaOrg/lbstanza/blob/0026d7f33b02891219d49730d6fa1f13ac5e9694/compiler/core-macros.stanza#L1569

It is not mentioned in either the reference or in this section about the match expression: 

https://lbstanza.org/chapter3.html#anchor24

Is this not intended to be an externally facing API ? I've seen it used in various places so I assume it is fair game to the end user.

**Comment by CuppoJava** [comment]
Thanks. It's just another case of missing documentation.
