### ISSUE TITLE
Document Build System

### ISSUE THREAD

**Issue by callendorph** [StanzaOrg/stanzasite#6]
Currently the build system and the syntax for the `stanza.proj` file seems only to be documented in `stanza/docs/build-system.md`. 

It would be really useful if this was documented in the reference page as well. Copying and pasting doesn't seem like the best plan. Do you have plan for how to include this information in a more indexable form ?

**Comment by CuppoJava** [comment]
Absolute easiest path forward *is* probably to add some pages to the Reference section so that these can be documented. 

Longer term, I think it's past time to migrate beyond my non-standard doc system to a system like Sphinx or MdBook and make it easier to organize a larger base of documentation.
